repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--exclude=venv,.venv,__pycache__,.git"]